In [2]:
import numpy as np 

In [5]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

narr = np.array(arr)

In [6]:
narr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.ones(10) * 255

array([255., 255., 255., 255., 255., 255., 255., 255., 255., 255.])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])