In [2]:
import numpy as np

In [13]:
x = np.arange(10)

In [14]:
x[2]

2

In [15]:
x[1:3]

array([1, 2])

In [16]:
x[1:3] = 12

In [17]:
x

array([ 0, 12, 12,  3,  4,  5,  6,  7,  8,  9])

In [20]:
x_slice = x[4:8]
x_slice 

array([4, 5, 6, 7])

In [21]:
x_slice[-1] = -100
x_slice

array([   4,    5,    6, -100])

In [22]:
x

array([   0,   12,   12,    3,    4,    5,    6, -100,    8,    9])

In [26]:
y = np.array([[1, 2, 3],
               [4, 5, 6],
               [7,8,9]])
y


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
y[0][2]

3

In [28]:
y[0, 2]

3

In [29]:
y[0, :]

array([1, 2, 3])

In [30]:
y[1, :]

array([4, 5, 6])

In [31]:
y[:, 1]

array([2, 5, 8])

In [32]:
y[0:2, 2]

array([3, 6])

In [33]:
y[0:, 2]

array([3, 6, 9])

In [36]:
y[:2, :2]

array([[1, 2],
       [4, 5]])

In [37]:
y[:, [2, 1, 0]]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [38]:
y[:, [2, 0, 0]]

array([[3, 1, 1],
       [6, 4, 4],
       [9, 7, 7]])

In [39]:
y[:, 2::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [40]:
y[1:2, :2]

array([[4, 5]])

In [41]:
y[1, :2]

array([4, 5])