In [1]:
import numpy as np


In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
x + x 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
x*2


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
1 / x

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [7]:
x **2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
np.power(x, 2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [9]:
y = x + 10
y

array([[11, 12, 13],
       [14, 15, 16]])

In [10]:
x * y 

array([[11, 24, 39],
       [56, 75, 96]])

In [11]:
x @ y

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [12]:
y.T

array([[11, 14],
       [12, 15],
       [13, 16]])

In [13]:
y.T @ x

array([[ 67,  92, 117],
       [ 72,  99, 126],
       [ 77, 106, 135]])