In [65]:
import numpy as np 

# 1. use arange to create 10 int from -20 to 25 (inclusive) steps of 5
d = np.arange(-20, 26, 5)


In [66]:
# 2. multiply all values in d by 10, storing them in d2
d2 = d * 10

In [67]:
# 3. add the values stored in d and d2 printing them to console
print(d2 + d)

[-220 -165 -110  -55    0   55  110  165  220  275]


In [68]:
# 4. reshape d2 into 5x2 array 
d2 = d2.reshape((5, 2))

In [69]:
# 5. create an array d3, containing integers 1, 2, 3, 4, 5
d3 = np.arange(1, 6)

In [70]:
# 6. reshape d3 into the necessary shape such that d2 * d3 works
d4 = d3[:, np.newaxis] * d2
print(d4)

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]


In [71]:
# 7. print to the console the 1st, 3rd, and 5th rows, both columns of d4
print(d4[0])
print(d4[2])
print(d4[4])

[-200 -150]
[  0 150]
[1000 1250]


In [72]:
# 8. print the id of d4
print(id(d4))

543976752


In [73]:
# 9. resize (not reshape) d4 into 2x5
d4.resize((2, 5))

In [74]:
# 10. flatten (not reshape) d4 back into 10x1 array
print(d4.flatten())

[-200 -150 -200 -100    0  150  400  600 1000 1250]
